<?php


$lista_itens = array(

  'Agasalho Esportivo' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Agasalho Ginástica' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Agasalho Moleton' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Agasalho de Ginástica' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Almofada Grande' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Almofada Média' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Almofada Pequena' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Avental' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Bata' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Bermuda Praia / Piscina' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Bermuda de Brim / Jeans unisex' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Biquini' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Body' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Bolsa de Pano' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Boné' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Cachecol' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Calcinha' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Calça Moletom' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Calça Ski' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Calça de Brim / Jeans Infantil' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Calça de Brim / Jeans unisex' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Calça de Couro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Camisa Polo Unisex' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Camisa Social Unisex' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Camisa unisex' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Camiseta / Camisa infantil' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Camisola' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Canga' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Capa de Almofada' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Capa de Chuva' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Capa de Edredon' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Capa de Sofá 1 lugar' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Capa de Sofá 2 lugares' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Capa de Sofá 3 lugares' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Capa de Sofá 4 lugares' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Casaco' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Casaco Infantil' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Casaco Moletom' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Casaco Ski' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Casaco de Chuva' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Casaco de Pelos' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Casaquinho Feminino' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Chapéu Panamá' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Chinelo' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Cobertor Casal' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Cobertor Solteiro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Colcha Casal' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Colcha Solteiro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Conjunto de Moleton Adulto' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Conjunto de Moleton Infantil' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Cosário' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Cueca' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Edredom Pena de Ganso' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Edredon Casal / Queen' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Edredon King Size' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Edredon Solteiro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Fralda' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Fronha de Travesseiro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Gorro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Jaleco' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Jaqueta Jeans' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Jaqueta de Couro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Kimono' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Legging' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Lenço' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Lençol Casal' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Lençol Solteiro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Lingeri' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Lingeri / Babydoll' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Luva' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Luva Ski' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Macacão Ski' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Maiô' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Manta' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Meia' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Mochila' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Pijama Unisex' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Rede' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Roupas Íntimas' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Roupão' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Saia' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Samba Canção' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Sapato' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Shorts' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Sobretudo' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Sunga' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Sutiã' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Tapete de Banheiro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Toalha de Banho' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Toalha de Mão / Rosto' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Toalha de Rosto' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Top de Ginástica' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Travesseiro' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Travesseiro Nasa' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Tênis' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Vestido' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'Vestido de Festa' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),
'nome' => array( 0.00, 0.000, 1, array( $opcao_caracteristicas, $opcao_cores, $opcao_defeitos, $opcao_marca ) ),




);

//ksort($lista_itens);





 ?>
